# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello_world.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 731, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.alt_sp1_textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.alt_sp1_textEdit.setObjectName("alt_sp1_textEdit")
        self.gridLayout.addWidget(self.alt_sp1_textEdit, 1, 2, 1, 1)
        self.alt_sp2_textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.alt_sp2_textEdit.setObjectName("alt_sp2_textEdit")
        self.gridLayout.addWidget(self.alt_sp2_textEdit, 1, 4, 1, 1)
        self.nwa_textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.nwa_textEdit.setObjectName("nwa_textEdit")
        self.gridLayout.addWidget(self.nwa_textEdit, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.nwa_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nwa_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nwa_label.setObjectName("nwa_label")
        self.gridLayout.addWidget(self.nwa_label, 0, 0, 1, 1)
        self.alt_sp2_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.alt_sp2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_sp2_label.setObjectName("alt_sp2_label")
        self.gridLayout.addWidget(self.alt_sp2_label, 0, 4, 1, 1)
        self.alt_sp1_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.alt_sp1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_sp1_label.setObjectName("alt_sp1_label")
        self.gridLayout.addWidget(self.alt_sp1_label, 0, 2, 1, 1)
        self.alt_sp3_textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.alt_sp3_textEdit.setObjectName("alt_sp3_textEdit")
        self.gridLayout.addWidget(self.alt_sp3_textEdit, 1, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        self.alt_sp3_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.alt_sp3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alt_sp3_label.setObjectName("alt_sp3_label")
        self.gridLayout.addWidget(self.alt_sp3_label, 0, 7, 1, 1)
        self.phase_textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.phase_textEdit.setObjectName("phase_textEdit")
        self.gridLayout.addWidget(self.phase_textEdit, 1, 8, 1, 1)
        self.phase_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.phase_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phase_label.setObjectName("phase_label")
        self.gridLayout.addWidget(self.phase_label, 0, 8, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nwa_label.setText(_translate("MainWindow", "NWA Charge Number"))
        self.alt_sp2_label.setText(_translate("MainWindow", "Alternative SP2"))
        self.alt_sp1_label.setText(_translate("MainWindow", "Alternative SP1"))
        self.alt_sp3_label.setText(_translate("MainWindow", "Alternative SP3"))
        self.phase_label.setText(_translate("MainWindow", "Phase"))
